# Generated by Django 5.1.3 on 2024-11-08 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_qnty', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.CharField(max_length=12)),
                ('Prd_Name', models.CharField(max_length=200)),
                ('stck_qnty', models.IntegerField(default=0)),
                ('prc', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='POS.cartitem')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='prdct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='POS.product'),
        ),
    ]
